[package]
name = "recipe"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[lib]
path = "recipe.rs"

[[bin]]
name = "train"
path = "train.rs"

[features]
default = ["amd"]
amd = []
nvidia = []

[dependencies]

[package.metadata.recipe]
dependency-allowlist = []
hsa-architecture = "gfx1101"
hsa-compiler = "/opt/rocm/lib/llvm/bin/clang"
hsa-library = "/opt/rocm/lib"
hsa-device-library = "/opt/rocm/amdgcn/bitcode/ocml.bc"
hsa-isa-library = "/opt/rocm/amdgcn/bitcode/oclc_isa_version_1101.bc"
hsa-finite-library = "/opt/rocm/amdgcn/bitcode/oclc_finite_only_off.bc"
hsa-math-library = "/opt/rocm/amdgcn/bitcode/oclc_unsafe_math_off.bc"
nvidia-architecture = "sm_86"
nvidia-ptx = "ptx71"
nvidia-compiler = "/usr/bin/clang"
nvidia-library = "/usr/lib"
nvidia-device-library = "/opt/cuda/nvvm/libdevice/libdevice.10.bc"

[package.metadata.train]
epochs = 1
learning-rate = 0.01
finite-difference-step = 0.00001
kmeans-iterations = 8
gpu-threads = 64
output-tolerance = 0.00000001
gradient-tolerance = 0.00001
backend-tolerance = 0.00001
