[package]
name = "recipe"
version = "0.1.1"
edition = "2024"
description = "ML training + inference for AMD/NVIDIA GPUs"
license = "MIT"
repository = "https://github.com/nm-z/nates-recipe-rs"
readme = "README.md"
keywords = ["machine-learning", "gpu", "hip", "neural-network"]
categories = ["science::ml"]

[lib]
name = "recipe"
test = false
doctest = false

[[bin]]
name = "recipe"
path = "src/main.rs"
test = false

[[test]]
name = "all"
harness = false

[workspace]
resolver = "3"
members = [
	".",
	"recipe-infer",
	"pantry",
	"vramspy",
	"gpu-core",
	"log",
	"ogdl",
	"catboost-rs",
	"xgboost-rs",
	"lightgbm-rs",
]

[dependencies]
gpu-core = { path = "gpu-core" }
recipe-infer = { path = "recipe-infer" }
pantry = { path = "pantry" }
ogdl = { path = "ogdl" }
anyhow = "1"
csv = "1"
ndarray = { version = "0.16", features = ["rayon"] }
ndarray-stats = "0.6"
rayon = "1"
rand = "0.9"
rand_chacha = "0.9"
rand_distr = "0.5"
image = "0.25"
ratatui = "0.29"
crossterm = "0.28"
tui-textarea = "0.7"
unicode-width = "0.2"
libc = "0.2"
indicatif = { version = "0.17", features = ["rayon"] }
data-encoding = "2.11.0"
zip = "2"


[lints]
workspace = true

[dev-dependencies]
serde_json = "1"

[profile.release]
# overrides
overflow-checks = true
lto = "thin"
# defaults
opt-level = 3
debug = false
strip = "none"
debug-assertions = false
panic = "unwind"
incremental = false
codegen-units = 16
rpath = false

[profile.dev]
# overrides
opt-level = 1
# defaults
debug = true
strip = "none"
debug-assertions = true
overflow-checks = true
lto = false
panic = "unwind"
incremental = true
codegen-units = 256
rpath = false

[profile.dev.package."*"]
# overrides
debug = false

[workspace.lints.rust]
# overrides
unsafe_code = "warn"
# defaults
warnings = "warn"
unsafe_op_in_unsafe_fn = "warn"

[workspace.lints.clippy]
# overrides
correctness = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }
restriction = { level = "warn", priority = -1 }
blanket_clippy_restriction_lints = "allow"
needless_return = "allow"
# defaults
suspicious = { level = "warn", priority = -1 }
style = { level = "warn", priority = -1 }
complexity = { level = "warn", priority = -1 }
perf = { level = "warn", priority = -1 }
min_ident_chars = "allow"
indexing_slicing = "allow"
semicolon_outside_block = "allow"
arithmetic_side_effects = "allow"
question_mark_used = "allow"
pub_use = "allow"
single_char_lifetime_names = "allow"
inline_trait_bounds = "allow"
unseparated_literal_suffix = "allow"
float_arithmetic = "allow"
mod_module_files = "allow"
default_numeric_fallback = "allow"
as_conversions = "allow"
arbitrary_source_item_ordering = "allow"
impl_trait_in_params = "allow"
integer_division = "allow"
exhaustive_structs = "allow"
missing_trait_methods = "allow"
integer_division_remainder_used = "allow"
pub_without_shorthand = "allow"
pub_with_shorthand = "allow"



