# overrides
too-many-lines-threshold = 200
cognitive-complexity-threshold = 35
# defaults
too-many-arguments-threshold = 7
type-complexity-threshold = 250
trivial-copy-size-limit = 8
single-char-binding-names-threshold = 4
max-fn-params-bools = 3
max-struct-bools = 3
max-trait-bounds = 3
