//! Apples-to-apples architecture parity against llama.cpp, one row per model.
//!
//! Fixtures live in `datasets/llamacpp-archs-seed42/`, generated by the
//! llama.cpp clone's own harness (`test-llama-archs -s 42 -o <dir>`, one
//! process per arch): every saver-supported architecture as a tiny seeded
//! random-weight GGUF, plus that binary's CPU-backend logits for the shared
//! 128-token input (`tokens.txt`) as `<arch>-<cfg>.logits` (LGT0 header,
//! f32 LE, n_tokens x n_vocab row-major). Same seed, same files, both sides:
//! llama.cpp's own sweep passes on this GPU iff its device NMSE vs CPU is
//! <= 1e-4; this test holds recipe-infer's f64 forward to the IDENTICAL bar
//! against the IDENTICAL reference on the last position.
//!
//! Every model gets a verdict line on stderr as it completes:
//!   OK          NMSE <= 1e-4 vs the llama.cpp CPU reference
//!   FAIL        forward ran, NMSE > 1e-4
//!   UNSUPPORTED architecture not wired into recipe-infer's verified dispatch
//!   ERROR       load/forward returned an error
//!   NOREF       fixture gguf has no reference logits (llama.cpp itself
//!               cannot forward that arch on CPU; not counted against parity)
//!
//! The test passes only at FULL parity: every referenced model OK. It is
//! EXPECTED to fail while architectures remain unwired; the table is the
//! burn-down baseline.

use anyhow::{Context, Result, bail};
use recipe_infer::gguf::{Gguf, Val};
use recipe_infer::llm::{arch_composable, arch_supported, last_logits};
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

const NMSE_BAR: f64 = 1e-4;

fn fixtures_dir() -> PathBuf {
	Path::new(env!("CARGO_MANIFEST_DIR")).join("../datasets/llamacpp-archs-seed42")
}

fn read_tokens(dir: &Path) -> Result<Vec<u32>> {
	let text = fs::read_to_string(dir.join("tokens.txt")).context("tokens.txt")?;
	let mut toks = Vec::new();
	for line in text.lines().filter(|l| !l.trim().is_empty()) {
		toks.push(line.trim().parse::<u32>().with_context(|| format!("token line {line:?}"))?);
	}
	anyhow::ensure!(!toks.is_empty(), "tokens.txt empty");
	return Ok(toks);
}

fn read_ref_last(path: &Path) -> Result<Vec<f64>> {
	let raw = fs::read(path)?;
	anyhow::ensure!(raw.len() >= 12 && &raw[..4] == b"LGT0", "bad LGT0 header");
	let n_tokens = u32::from_le_bytes([raw[4], raw[5], raw[6], raw[7]]) as usize;
	let n_vocab = u32::from_le_bytes([raw[8], raw[9], raw[10], raw[11]]) as usize;
	anyhow::ensure!(
		raw.len() == 12 + n_tokens * n_vocab * 4,
		"LGT0 size mismatch: {} bytes for {n_tokens}x{n_vocab}",
		raw.len()
	);
	let last = &raw[12 + (n_tokens - 1) * n_vocab * 4..];
	return Ok(last
		.chunks_exact(4)
		.map(|c| f64::from(f32::from_le_bytes([c[0], c[1], c[2], c[3]])))
		.collect());
}

fn nmse(reference: &[f64], got: &[f64]) -> f64 {
	let mut num = 0.0;
	let mut den = 0.0;
	for (a, b) in reference.iter().zip(got.iter()) {
		num += (a - b) * (a - b);
		den += a * a;
	}
	return num / den;
}

fn gguf_arch(path: &Path) -> Result<String> {
	let g = Gguf::open(path)?;
	match g.kv.get("general.architecture") {
		Some(Val::Str(s)) => return Ok(s.clone()),
		other => bail!("general.architecture missing or non-string: {other:?}"),
	}
}

#[test]
fn archs_parity_vs_llama_cpp() {
	let dir = fixtures_dir();
	let toks = read_tokens(&dir).expect("fixture tokens");
	let mut models: Vec<PathBuf> = fs::read_dir(&dir)
		.expect("fixtures dir")
		.filter_map(|e| e.ok().map(|e| e.path()))
		.filter(|p| p.extension().is_some_and(|x| x == "gguf"))
		.collect();
	models.sort();
	assert!(!models.is_empty(), "no gguf fixtures in {}", dir.display());

	let (mut ok, mut fail, mut unsup, mut err, mut noref) = (0u32, 0u32, 0u32, 0u32, 0u32);
	let mut clean: HashMap<String, bool> = HashMap::new();
	eprintln!("{:<20} {:<6} {}", "Model arch.", "Config", "recipe-infer vs llama.cpp");
	for gguf in &models {
		let stem = gguf.file_stem().and_then(|s| s.to_str()).unwrap_or("?");
		let (name, cfg) = match stem.rsplit_once('-') {
			Some((n, c)) => (n, c),
			None => (stem, "?"),
		};
		let refpath = gguf.with_extension("logits");
		let verdict = if !refpath.exists() {
			noref += 1;
			"\x1b[1;33mNOREF\x1b[0m".to_string()
		} else {
			match gguf_arch(gguf) {
				Err(e) => {
					err += 1;
					format!("\x1b[1;31mERROR\x1b[0m {e:#}")
				}
				Ok(arch) if !arch_composable(&arch) => {
					unsup += 1;
					"\x1b[1;33mUNSUPPORTED\x1b[0m".to_string()
				}
				Ok(_arch) => match (read_ref_last(&refpath), last_logits(gguf, &toks)) {
					(Ok(reference), Ok(got)) if reference.len() == got.len() => {
						let e = nmse(&reference, &got);
						if e <= NMSE_BAR {
							ok += 1;
							format!("\x1b[1;32mOK\x1b[0m ({e:.2e})")
						} else {
							fail += 1;
							format!("\x1b[1;31mFAIL\x1b[0m ({e:.2e})")
						}
					}
					(Ok(reference), Ok(got)) => {
						err += 1;
						format!(
							"\x1b[1;31mERROR\x1b[0m vocab mismatch ref {} vs got {}",
							reference.len(),
							got.len()
						)
					}
					(Err(e), _) | (_, Err(e)) => {
						err += 1;
						format!("\x1b[1;31mERROR\x1b[0m {e:#}")
					}
				},
			}
		};
		eprintln!("{name:<20} {cfg:<6} {verdict}");
		if refpath.exists()
			&& let Ok(arch) = gguf_arch(gguf)
		{
			let all_ok = clean.entry(arch).or_insert(true);
			*all_ok &= verdict.starts_with("\x1b[1;32mOK");
		}
	}
	let referenced = ok + fail + unsup + err;
	eprintln!(
		"parity: {ok} OK, {fail} FAIL, {unsup} UNSUPPORTED, {err} ERROR of {referenced} referenced ({noref} NOREF)"
	);
	let regressions: Vec<&str> = recipe_infer::llm::supported_archs()
		.iter()
		.copied()
		.filter(|a| clean.get(*a).is_some_and(|c| !c))
		.collect();
	assert!(
		regressions.is_empty(),
		"VERIFIED arch regressed from measured OK: {regressions:?}"
	);
	let mut promotable: Vec<&String> = clean
		.iter()
		.filter(|(a, c)| **c && !arch_supported(a))
		.map(|(a, _c)| a)
		.collect();
	promotable.sort();
	if !promotable.is_empty() {
		eprintln!("promotable to VERIFIED (all configs OK): {promotable:?}");
	}
	assert_eq!(
		(fail, unsup, err),
		(0, 0, 0),
		"full parity not reached: {ok}/{referenced} models match llama.cpp (NMSE <= {NMSE_BAR:.0e})"
	);
}
